routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*App\User::create([
	'name' => 'Maria',
	'email' => 'maria@mail.com',
	'password' => bcrypt('123456')
]);*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');

Route::get('roles', function() {
    return App\Role::with('user')->get();
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = ['nombre', 'email', 'mensaje'];
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    public function user()
    {
    	return $this->hasMany(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class, 'assigned_roles');
    }

    public function hasRoles(array $roles)
    {
        return $this->roles->pluck('name')->intersect($roles)->count();
    }


    public function isAdmin()
    {
        return $this->hasRoles(['admin']);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use DB;

use App\Message;

use Carbon\Carbon;

use Illuminate\Http\Request;

class MessagesController extends Controller
{

    function __construct()
    {
        $this->middleware('auth', ['except' => ['create', 'store']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$messages = DB::table('messages')->get();

        $messages = Message::all();

        return view('messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validacion del Request
        $this->validate($request, [
            'nombre' => 'required',
            'email' => 'required|email',
            'mensaje' => 'min:4'
        ]);
        // Guardar mensaje
        // DB::table('messages')->insert([
        //     'nombre' => $request->nombre,
        //     'email' => $request->email,
        //     'mensaje' => $request->mensaje,
        //     'created_at' => Carbon::now(),
        //     'updated_at' => Carbon::now()
        // ]);

        Message::create([
            'nombre' => $request->nombre,
            'email' => $request->email,
            'mensaje' => $request->mensaje
        ]);
        // Redireccionar mensaje

        return redirect()->route('mensajes.create')->with('info', 'Hemos recibido tu mensaje');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $message = Message::findOrFail($id);

        return view('messages.show', compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $message = Message::findOrFail($id);

        return view('messages.edit', compact('message'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Actualizar
        // DB::table('messages')->where('id', $id)->update([
        //     'nombre' => $request->nombre,
        //     'email' => $request->email,
        //     'mensaje' => $request->mensaje,
        //     'updated_at' => Carbon::now()
        // ]);

        $message = Message::findOrFail($id);

        $message->update([
            'nombre' => $request->nombre,
            'email' => $request->email,
            'mensaje' => $request->mensaje
        ]);

        // Redireccionar
        return redirect()->route('mensajes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Eliminar mensaje
        $message = Message::findOrFail($id)->delete();
        
        // Redireccionar
        return redirect()->route('mensajes.index');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;

class UsersController extends Controller
{

    function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
        $this->middleware('roles:admin', ['except' => ['edit', 'update', 'show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $this->authorize('edit', $user);

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email,'.$id
        ]);

        $user = User::findOrFail($id);

        $this->authorize('update', $user);

        $user->update($request->all());

        return back()->with('info', 'Usuairo actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        
        $this->authorize('destroy', $user);

        $user->delete();

        return back();
    }
}

resources/views/messages/create.blade.php
@extends('welcome')

@section('content')
	<h1>Contacto</h1>
	<h4>Escríbeme un mensaje</h4>
	<br>
	@if (session('info'))
		<h1>{{ session('info') }}</h1>
	@endif
	<form action="{{ route('mensajes.store') }}" method="post">
		{{ csrf_field() }}
		<div class="form-group">
			<label for="nombre">Nombre</label>
			<input type="text" class="from-control" name="nombre" value="{{ old('nombre') }}">
			{{ $errors->first('nombre') }}
		</div>
		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" class="from-control" name="email" value="{{ old('email') }}">
			{{ $errors->first('email') }}
		</div>
		<div class="form-group">
			<label for="mensaje">Mensaje</label>
			<textarea name="mensaje" class="from-control">{{ old('mensaje') }}</textarea>
			{{ $errors->first('mensaje') }}
		</div>
		<input type="submit" value="Enviar" class="btn btn-primary">
	</form>
@endsection

resources/views/messages/edit.blade.php
@extends('welcome')

@section('content')
	<h1>Editar mensaje de {{ $message->nombre }}</h1>
	<hr>
	<form action="{{ route('mensajes.update', $message->id) }}" method="post">
		{{ method_field('PUT') }}
		{{ csrf_field() }}
		<div class="form-group">
			<label for="nombre">Nombre</label>
			<input type="text" class="from-control" name="nombre" value="{{ $message->nombre }}">
			{{ $errors->first('nombre') }}
		</div>
		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" class="from-control" name="email" value="{{ $message->email }}">
			{{ $errors->first('email') }}
		</div>
		<div class="form-group">
			<label for="mensaje">Mensaje</label>
			<textarea name="mensaje" class="from-control">{{ $message->mensaje }}</textarea>
			{{ $errors->first('mensaje') }}
		</div>
		<input type="submit" value="Enviar" class="btn btn-primary">
	</form>
@endsection

resources/views/messages/index.blade.php
@extends('welcome')

@section('content')
	<h1>Todos los mensajes</h1>
	<hr>
	<table class="table">
		<thead>
			<th>ID</th>
			<th>Nombre</th>
			<th>Email</th>
			<th>Mensaje</th>
			<th>Acciones</th>
		</thead>
		<tbody>
			@foreach ($messages as $message)
				<tr>
					<td>{{ $message->id }}</td>
					<td>
						<a href="{{ route('mensajes.show', $message->id) }}">
							{{ $message->nombre }}
						</a>
					</td>
					<td>{{ $message->email }}</td>
					<td>{{ $message->mensaje }}</td>
					<td>
						<a href="{{ route('mensajes.edit', $message->id) }}" class="btn btn-info btn-xs">Editar</a>
						<form style="display: inline;" action="{{ route('mensajes.destroy', $message->id) }}"  method="POST">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}

							<button type="submit" class="btn btn-danger btn-xs">Eliminar</button>
						</form>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection

resources/views/messages/show.blade.php
@extends('welcome')

@section('content')
	<h1>Mensaje</h1>
	<hr>
	<p>Enviado por {{ $message->nombre }} - {{ $message->email }}</p>
	<p>{{ $message->mensaje }}</p>
@endsection

resources/views/users/edit.blade.php
@extends('welcome')

@section('content')
	<h1>Editar usuario</h1>
	<hr>
	@if (session()->has('info'))
		<div class="alert alert-success">
			{{ session('info') }}
		</div>
	@endif
	<form action="{{ route('usuarios.update', $user->id) }}" method="post">
		{{ method_field('PUT') }}
		{{ csrf_field() }}
		<div class="form-group">
			<label for="name">Nombre</label>
			<input type="text" class="from-control" name="name" value="{{ $user->name }}">
			{{ $errors->first('name') }}
		</div>
		<div class="form-group">
			<label for="email">Email</label>
			<input type="email" class="from-control" name="email" value="{{ $user->email }}">
			{{ $errors->first('email') }}
		</div>
		<input type="submit" value="Enviar" class="btn btn-primary">
	</form>
@endsection

resources/views/users/index.blade.php
@extends('welcome')

@section('content')
	<h1>Usuarios</h1>
	<table class="table">
		<thead>
			<th>ID</th>
			<th>Nombre</th>
			<th>Email</th>
			<th>Role</th>
			<th>Acciones</th>
		</thead>
		<tbody>
			@foreach ($users as $user)
				<tr>
					<td>{{ $user->id }}</td>
					<td>{{ $user->name }}</td>
					<td>{{ $user->email }}</td>
					<td>
						{{ $user->roles->pluck('display_name')->implode(', ') }}
					</td>
					<td>
						<a 
						href="{{ route('usuarios.edit', $user->id) }}" 
						class="btn btn-info btn-xs">Editar</a>
						<form style="display: inline;" 
							action="{{ route('usuarios.destroy', $user->id) }}"  method="POST">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}

							<button type="submit" class="btn btn-danger btn-xs">Eliminar</button>
						</form>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@endsection

resources/views/users/show.blade.php
@extends('welcome')

@section('content')
	<h1>
		{{ $user->name }}
	</h1>
	<table class="table">
		<tr>
			<th>Nombre:</th>
			<td>{{ $user->name }}</td>
		</tr>
		<tr>
			<th>Email:</th>
			<td>{{ $user->email }}</td>
		</tr>
		<tr>
			<th>Roles:</th>
			<td>
				@foreach ($user->roles as $role)
					{{ $role->display_name }}
				@endforeach
			</td>
		</tr>
	</table>

	@can('edit', $user)
	    <a href="{{ route('usuarios.edit', $user->id) }}" class="btn btn-info">Editar</a>
	@endcan

	@can('destroy', $user)
	    <form style="display: inline;" 
			action="{{ route('usuarios.destroy', $user->id) }}"  method="POST">
			{{ csrf_field() }}
			{{ method_field('DELETE') }}

			<button type="submit" class="btn btn-danger">Eliminar</button>
		</form>
@endcan
@endsection